$(document).ready(function(){
	$("#itu1").mouseenter(function(){
		$("#foto").fadeOut();
	});
	$("#itu1").mouseleave(function(){
		$("#foto").fadeIn();
	});
	$("#itu2").mouseenter(function(){
		$("#foto2").fadeOut();
	});
	$("#itu2").mouseleave(function(){
		$("#foto2").fadeIn();
	});
	$("#itu3").mouseenter(function(){
		$("#foto3").fadeOut();
	});
	$("#itu3").mouseleave(function(){
		$("#foto3").fadeIn();
	});
	$("#itu4").mouseenter(function(){
		$("#foto4").fadeOut();
	});
	$("#itu4").mouseleave(function(){
		$("#foto4").fadeIn();
	});
	$("#itu5").mouseenter(function(){
		$("#foto5").fadeOut();
	});
	$("#itu5").mouseleave(function(){
		$("#foto5").fadeIn();
	});
	$("#itu6").mouseenter(function(){
		$("#foto6").fadeOut();
	});
	$("#itu6").mouseleave(function(){
		$("#foto6").fadeIn();
	});
	$("#itu7").mouseenter(function(){
		$("#foto7").fadeOut();
	});
	$("#itu7").mouseleave(function(){
		$("#foto7").fadeIn();
	});
	$("#itu8").mouseenter(function(){
		$("#foto8").fadeOut();
	});
	$("#itu8").mouseleave(function(){
		$("#foto8").fadeIn();
	});
	$("#itu9").mouseenter(function(){
		$("#foto9").fadeOut();
	});
	$("#itu9").mouseleave(function(){
		$("#foto9").fadeIn();
	});
});